'use client';
import {useCallback,useEffect,useRef,useState,type DragEvent} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,ArrowDown,Plus,ChevronRight,ChevronDown,FileText,Bookmark,Check,ShieldCheck,GitBranch,Download,LoaderCircle,X,Code2,CheckCircle2,AlertCircle,Pencil,Play,Square,History,Menu,BookOpen,Lock,MessagesSquare,Route,RotateCcw,FolderOpen,Sparkles,CornerDownRight,Send,ClipboardCheck} from 'lucide-react';
import {api,previewMode} from '@/lib/api';
import {stages,workflowSteps,stepIndex,type Project,type AppData} from '@/lib/types';
const stepIcons=[FileText,MessagesSquare,ClipboardCheck,FileText,ShieldCheck,Bookmark,Code2,CheckCircle2];
const template='# 我的 AI 产品\n\n## 目标用户与核心任务\n谁在什么场景下，用它完成什么任务？\n\n## 输入、流程与产物\n用户提供什么？哪些步骤需要确认？最终得到什么？\n\n## 验收标准\n什么算做好？由谁来判断？\n\n## 第一版优先级\nMVP 必须做什么？哪些可以后做？\n\n## 模型、费用与数据\n模型偏好、成本上限和隐私边界是什么？\n\n## 上线与账号\n内部试用还是对外开放？登录与预算要求是什么？';
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function time(value:string){return new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
function Markdown({text}:{text:string}){return <div className="markdown">{text.split('\n').map((line,i)=>line.startsWith('# ')?<h2 key={i}>{line.slice(2)}</h2>:line.startsWith('## ')?<h3 key={i}>{line.slice(3)}</h3>:line.startsWith('### ')?<h4 key={i}>{line.slice(4)}</h4>:line.startsWith('> ')?<blockquote key={i}>{line.slice(2)}</blockquote>:line.startsWith('- ')?<div className="md-bullet" key={i}><span>•</span><span>{line.slice(2)}</span></div>:line.trim()?<p key={i}>{line}</p>:<div className="md-space" key={i}/>)}</div>;}
type Action=(body:Record<string,unknown>)=>Promise<void>;
function Questions({p,busy,act}:{p:Project;busy:boolean;act:Action}){
 const[answers,setAnswers]=useState<Record<string,string>>({});
 return <><div className="conversation-intro"><span className="ai-avatar"><Sparkles size={19}/></span><div><strong>我读完了你的 PRD，有几个地方想和你对齐。</strong><p>这一轮只回答下面 {p.questions.length} 个问题。可以按推荐，也可以写自己的想法。</p></div></div><div className="questions">{p.questions.map((q,i)=><section className="question-card" key={q.id}><div className="question-title"><span>0{i+1}</span><h3>{q.question}</h3></div><p className="question-reason">{q.reason}</p><div className="answer-options">{q.options.map(option=><button className={answers[q.id]===option?'chosen':''} key={option} onClick={()=>setAnswers(a=>({...a,[q.id]:option}))}><span className="radio-circle"/>{option}{answers[q.id]===option&&<Check size={15}/>}</button>)}</div>{q.recommendation&&<div className="recommendation"><Sparkles size={14}/><span>推荐：{q.recommendation}</span><button onClick={()=>setAnswers(a=>({...a,[q.id]:q.recommendation}))}>按推荐</button></div>}<label htmlFor={`answer-${q.id}`}>你的补充</label><textarea id={`answer-${q.id}`} placeholder="也可以写自己的答案，暂时没想好就填“不确定”" value={answers[q.id]||''} onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))}/>{q.impact&&<p className="question-impact">需要明确的原因：{q.impact}</p>}</section>)}</div><div className="flow-action"><div><span>先把需求说明白</span><small>提交后模型继续检查；还有关键缺口会再提问</small></div><button className="button primary" disabled={busy||p.questions.some(q=>!answers[q.id]?.trim())} onClick={()=>void act({action:'answer',answers})}>提交回答，继续澄清<Send size={16}/></button></div></>;
}
function Requirements({p,busy,act}:{p:Project;busy:boolean;act:Action}){const[checked,setChecked]=useState(false),[adding,setAdding]=useState(false),[note,setNote]=useState('');return <><div className="context-note"><CheckCircle2 size={18}/><span>模型已完成 {p.interviewTurn} 轮需求检查。下面是依据 PRD 和你的回答整理的需求确认单。</span></div><div className="document-body"><Markdown text={p.requirementSummary}/></div>{adding?<div className="feedback-form"><label htmlFor="requirement-note">还有哪里需要调整？</label><textarea id="requirement-note" value={note} onChange={e=>setNote(e.target.value)} placeholder="例如：第一版只面向内部同事，不需要公开注册。"/><button className="button secondary" disabled={busy||!note.trim()} onClick={()=>void act({action:'supplement',note})}>补充需求，让模型重新整理<ArrowRight size={16}/></button></div>:<button className="subtle-action" onClick={()=>setAdding(true)}><Pencil size={15}/>需求还不准确，我想补充</button>}<div className="confirmation-area"><label className="confirm-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>我确认目标用户、核心流程、交付范围、成本与验收标准符合预期。</span></label></div><div className="flow-action"><div><span>确认的是“做什么”</span><small>确认后才会生成“怎么做”的技术文档</small></div><button className="button primary" disabled={busy||!checked} onClick={()=>void act({action:'confirm_requirements',requirementsHash:p.requirementsHash,confirmed:true})}>确认需求，生成技术文档<ArrowRight size={16}/></button></div></>;}
function DocumentReview({p,busy,act}:{p:Project;busy:boolean;act:Action}){const[editing,setEditing]=useState(false),[draft,setDraft]=useState(p.document),[feedback,setFeedback]=useState(''),[revising,setRevising]=useState(false),[checked,setChecked]=useState(false);return <><div className="document-toolbar"><div><FileText size={18}/><strong>第 {p.round} 轮 · {stages[p.stage].name}</strong><span className="version">v{p.version}</span></div><div><button className="icon-button" aria-label="下载本轮技术文档" onClick={()=>download(`${p.name}-第${p.round}轮技术文档.md`,p.document)}><Download size={17}/></button><button className="button small-button secondary" onClick={()=>setEditing(!editing)}><Pencil size={14}/>{editing?'取消编辑':'直接编辑'}</button></div></div>{editing?<div className="feedback-form"><label htmlFor="plan-editor">编辑本轮技术文档</label><textarea className="plan-editor" id="plan-editor" value={draft} onChange={e=>setDraft(e.target.value)}/><button className="button primary" disabled={busy||draft.trim().length<100} onClick={()=>void act({action:'revise',document:draft})}>保存文档，重新审阅</button></div>:<div className="document-body"><Markdown text={p.document}/></div>}{revising?<div className="feedback-form"><label htmlFor="plan-feedback">告诉模型需要调整什么</label><textarea id="plan-feedback" value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="例如：这轮先不做登录，把文件上传和结果导出跑通。"/><button className="button secondary" disabled={busy||!feedback.trim()} onClick={()=>void act({action:'request_revision',feedback})}>让模型修改文档<ArrowRight size={16}/></button></div>:<button className="subtle-action" onClick={()=>setRevising(true)}><MessagesSquare size={15}/>方案需要调整，给模型提意见</button>}<div className="confirmation-area"><label className="confirm-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/><span>我已审阅本轮实现范围、技术适配、额外费用与验收标准，确认可以按此文档开发。</span></label></div><div className="flow-action"><div><span>文档确认后，还要保存书签</span><small>此操作不会启动开发</small></div><button className="button primary" disabled={busy||!checked||editing} onClick={()=>void act({action:'confirm_document',version:p.version,docHash:p.docHash,confirmed:true})}>确认文档，进入代码书签<ArrowRight size={16}/></button></div></>;}
function Review({p,busy,act}:{p:Project;busy:boolean;act:Action}){const[checks,setChecks]=useState([false,false]),[next,setNext]=useState<'same'|'next'>('same'),[feedback,setFeedback]=useState(''),[fix,setFix]=useState(false);return <><div className="context-note"><CheckCircle2 size={18}/><span>本轮执行已结束，请核对真实成果。下一轮文档尚未生成。</span></div><div className="document-body"><Markdown text={p.result||'请查看本轮项目文件与验证证据。'}/></div>{fix?<div className="feedback-form"><label htmlFor="fix-feedback">描述本轮还需修正的问题</label><textarea id="fix-feedback" value={feedback} onChange={e=>setFeedback(e.target.value)}/><button className="button secondary" disabled={busy||!feedback.trim()} onClick={()=>void act({action:'request_revision',feedback})}>退回本轮技术文档<ArrowRight size={15}/></button></div>:<button className="subtle-action" onClick={()=>setFix(true)}><RotateCcw size={15}/>没有达到预期，退回修改方案</button>}<div className="confirmation-area">{['已核对本轮功能与产物，符合确认过的技术文档。','已核对测试与证据，没有阻止本轮验收的未通过或待验项。'].map((label,i)=><label className="confirm-check" key={label}><input type="checkbox" checked={checks[i]} onChange={e=>setChecks(c=>c.map((v,j)=>j===i?e.target.checked:v))}/><span>{label}</span></label>)}<div className="next-round-choice"><strong>验收通过后，下一轮做什么？</strong><label><input type="radio" name="next-round" checked={next==='same'} onChange={()=>setNext('same')}/>继续完善「{stages[p.stage].name}」的下一个子阶段</label><label><input type="radio" name="next-round" checked={next==='next'} onChange={()=>setNext('next')}/>{p.stage===5?'全部交付，完成项目':`本阶段完成，进入「${stages[p.stage+1].name}」`}</label></div></div><div className="flow-action"><div><span>下一轮仍然先出文档</span><small>不会连续自动开发</small></div><button className="button primary" disabled={busy||!checks.every(Boolean)} onClick={()=>void act({action:'accept',verified:true,next})}>{p.stage===5&&next==='next'?'确认验收，完成项目':'验收通过，进入下一轮文档'}<ArrowRight size={16}/></button></div></>;}
function Records({p}:{p:Project}){return <div className="records-view"><div className="records-intro"><History size={23}/><div><h2>沿着流程，回看每次决定</h2><p>文档、确认和书签归属于同一轮开发。</p></div></div><details className="record-item"><summary><FileText size={17}/><strong>最初的 PRD</strong><span>{p.filename}</span><ChevronDown size={15}/></summary><Markdown text={p.prd}/></details>{p.interview.map((r,i)=><details className="record-item" key={i}><summary><MessagesSquare size={17}/><strong>第 {r.turn} 轮需求问答</strong><span>{r.questions.length} 个问题</span><ChevronDown size={15}/></summary>{r.questions.map(q=><div className="record-answer" key={q.id}><strong>{q.question}</strong><p>{r.answers[q.id]}</p></div>)}</details>)}{p.requirementsConfirmedAt&&<details className="record-item"><summary><ClipboardCheck size={17}/><strong>已确认需求</strong><span>{time(p.requirementsConfirmedAt)}</span><ChevronDown size={15}/></summary><Markdown text={p.requirementSummary}/></details>}{Array.from(new Set([...p.documents.map(d=>d.round),...p.bookmarks.map(b=>b.round)])).sort((a,b)=>b-a).map(round=><section className="round-record" key={round}><h3><span>{String(round).padStart(2,'0')}</span>第 {round} 轮开发记录</h3>{p.documents.filter(d=>d.round===round).map(d=><details className="record-item" key={`${d.version}-${d.createdAt}`}><summary><FileText size={16}/><strong>技术文档 v{d.version}</strong><span>{p.approvals.some(a=>a.round===round&&a.docHash===d.docHash)?'已确认':d.round===p.round&&d.version===p.version?'待确认':'历史版本'}</span><ChevronDown size={15}/></summary><Markdown text={d.document}/><button className="button secondary" onClick={()=>download(`第${round}轮-v${d.version}.md`,d.document)}><Download size={15}/>下载文档</button></details>)}{p.bookmarks.filter(b=>b.round===round).map(b=><div className="record-bookmark" key={b.id}><Bookmark size={18}/><div><strong>开发前代码书签</strong><p><code>{b.commit.slice(0,7)}</code> · {time(b.createdAt)} · {b.files} 个文件</p></div><>{previewMode?<button className="button small-button secondary" onClick={()=>download(`演示流程快照-${b.id}.json`,JSON.stringify({demo:true,note:'非 Git 代码快照',bookmark:b,documents:p.documents.filter(d=>d.round===b.round)},null,2))}><Download size={14}/>演示记录</button>:<a className="button small-button secondary" href={`/api/projects/${p.id}?bookmark=${b.id}`} download><Download size={14}/>下载</a>}</></div>)}</section>)}<details className="record-item"><summary><History size={17}/><strong>完整推进记录</strong><ChevronDown size={15}/></summary><div className="event-list">{p.activities.map(a=><div key={a.id}><span className={`activity-dot ${a.kind}`}/><section><h4>{a.title}</h4><p>{a.detail}</p><time>{time(a.time)}</time></section></div>)}</div></details></div>;}
export default function Studio(){
 const[data,setData]=useState<AppData>({projects:[],runner:{available:false,name:'正在连接'}}),[project,setProject]=useState<Project|null>(null);
 const[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[view,setView]=useState<'flow'|'history'>('flow');
 const[uploading,setUploading]=useState(false),[drag,setDrag]=useState(false),[busy,setBusy]=useState(false),[mobile,setMobile]=useState(false),[help,setHelp]=useState(false),[devConsent,setDevConsent]=useState(false);
 const input=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null),uploadLock=useRef(false),actionLock=useRef(false);
 const refresh=useCallback(async()=>{try{const next=await api.list();setData(next);const id=new URLSearchParams(window.location.search).get('project');setProject(id?next.projects.find(p=>p.id===id)||null:null);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{let active=true;api.list().then(next=>{if(!active)return;setData(next);const id=new URLSearchParams(window.location.search).get('project');if(id)setProject(next.projects.find(p=>p.id===id)||null);}).catch(e=>{if(active)setError((e as Error).message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 useEffect(()=>{if(!project||project.status!=='running')return;let active=true;const timer=setInterval(()=>{api.get(project.id).then(p=>{if(active){setProject(p);setData(d=>({...d,projects:d.projects.map(v=>v.id===p.id?p:v)}));}}).catch(()=>{if(active)setError('暂时无法连接本机服务，重新连接后可恢复进度。');});},2000);return()=>{active=false;clearInterval(timer);};},[project]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{if(help&&!dialog.current?.open)dialog.current?.showModal();else if(!help&&dialog.current?.open)dialog.current.close();},[help]);
 function choose(p:Project|null){setProject(p);setView('flow');setMobile(false);setError('');setDevConsent(false);window.history.replaceState(null,'',p?`${window.location.pathname}?project=${p.id}`:window.location.pathname);}
 function update(p:Project){setProject(p);setData(d=>({...d,projects:[p,...d.projects.filter(v=>v.id!==p.id)]}));}
 async function upload(file?:File){if(!file||uploadLock.current)return;uploadLock.current=true;setUploading(true);setError('');try{const p=await api.upload(file);update(p);choose(p);setToast('PRD 已导入，进入模型提问');}catch(e){setError((e as Error).message);}finally{uploadLock.current=false;setUploading(false);if(input.current)input.current.value='';}}
 function drop(e:DragEvent){e.preventDefault();setDrag(false);if(e.dataTransfer.files.length!==1){setError('请一次拖入一份 PRD');return;}void upload(e.dataTransfer.files[0]);}
 async function act(body:Record<string,unknown>){if(!project||actionLock.current)return;actionLock.current=true;setBusy(true);setError('');try{const p=await api.action(project.id,{...body,revision:project.revision});update(p);setDevConsent(false);setToast(body.action==='confirm_document'?'文档已确认，下一步保存书签':body.action==='bookmark'?'代码书签已保存，下一步按文档开发':body.action==='revise'?'文档已更新，请重新确认':'已记录，流程继续');}catch(e){setError((e as Error).message);}finally{setBusy(false);actionLock.current=false;}}
 const current=project?stepIndex(project):0;
 const title=project?.workflow==='ready'?'代码书签已保存，可以开始本轮开发':project?.workflow==='completed'?'项目已完成':workflowSteps[current]?.label||'导入 PRD';
 const descriptions=['带上一份 PRD。模型会先理解你的想法，并提出需要澄清的问题。','先回答模型的问题，把需求补充清楚。此时还不会生成技术文档。','请核对模型整理的需求。确认后，才开始讨论具体实现。','模型依据已确认需求和项目现状，编写这一轮的技术方案。','确认“这一轮怎么做”。有任何不合适的地方，先调整文档。','技术文档已经确认。现在保存当前代码，再进入开发。','文档和书签已就绪。模型只执行本轮已确认的范围。','先检查本轮成果。验收通过，再回到下一轮技术文档。'];
 return <div className="app-shell sequential-app"><aside className={`sidebar ${mobile?'mobile-open':''}`}><Link className="brand" href="/" onClick={e=>{e.preventDefault();choose(null);}}><span className="brand-mark"><Code2 size={24}/></span><div>Starter<span>STUDIO</span></div></Link><div className="workspace-picker"><span className="workspace-avatar">我</span><div>我的工作空间<small>本地工作区</small></div><ChevronDown size={15}/></div><div className="nav-label">当前项目</div><button className={`nav-item ${view==='flow'?'selected':''}`} onClick={()=>{setView('flow');setMobile(false);}}><Route size={18}/>搭建流程</button><button className={`nav-item ${view==='history'?'selected':''}`} disabled={!project} onClick={()=>{setView('history');setMobile(false);}}><History size={18}/>项目记录</button><div className="nav-label project-label">我的项目<button aria-label="新建项目" onClick={()=>choose(null)}><Plus size={16}/></button></div><div className="project-list">{data.projects.length?data.projects.map(p=><button className={`project-item ${p.id===project?.id?'active':''}`} key={p.id} onClick={()=>choose(p)}><span className="project-dot"/>{p.name}</button>):<p className="no-project">第一份 PRD，<br/>就是新项目的起点。</p>}</div><div className="sidebar-bottom"><div className="sidebar-note"><Route size={19}/><strong>一步完成，再往前一步</strong><p>先对齐需求，再确认方案。<br/>每轮开发前，都有代码书签。</p></div><button className="help-button" onClick={()=>setHelp(true)}><BookOpen size={17}/>了解完整流程<ArrowUpRight size={15}/></button><div className="profile"><span className="profile-avatar"><CommandIcon/></span><div>{data.runner.name}<small>{data.runner.available?'仅在当前步骤调用':'等待连接'}</small></div><span className="local-dot"/></div></div></aside>{mobile&&<button className="mobile-backdrop" aria-label="关闭菜单" onClick={()=>setMobile(false)}/>}
 <main className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="mobile-toggle icon-button" aria-label="打开菜单" onClick={()=>setMobile(true)}><Menu size={20}/></button><span>工作空间</span><ChevronRight size={14}/><strong>{project?.name||'新建项目'}</strong></div><div className="top-actions"><span className="local-badge"><span/>{previewMode?'在线流程演示':'本地运行'}</span><a className="icon-button repo-link" aria-label="查看原始仓库" href="https://github.com/hubooooooo/ai-product-starter-kit" target="_blank" rel="noreferrer"><GitBranch size={18}/></a></div></header>
 <div className="content flow-content">{previewMode&&<div className="preview-notice"><div><strong>在线流程演示</strong><p>可拖入 Markdown / TXT 体验顺序确认。内容仅保存在此浏览器；提问和方案为示例，不调用模型、不生成代码、不创建 Git 书签。</p></div><a className="button secondary" href="https://github.com/owenmao-builder/starter-studio#启动">运行完整版本<ArrowUpRight size={15}/></a></div>}<div className="page-heading"><div><div className="eyebrow">{project?'ONE STEP AT A TIME':'FROM PRD TO PRODUCT'}</div><h1>{project?.name||'先对齐想法，再一步步开发。'}</h1><p>{project?'沿着同一条流程，把每一次讨论变成明确的下一步。':'从一份 PRD 开始。每一步有来处，也有清晰的下一步。'}</p></div>{project&&<button className="button secondary new-project" onClick={()=>choose(null)}><Plus size={15}/>新项目</button>}</div>
 <input ref={input} type="file" accept={previewMode?'.md,.txt':'.md,.txt,.pdf,.docx'} className="file-input" aria-label="上传 PRD 文件" onChange={e=>void upload(e.target.files?.[0])}/>
 {error&&<div className="error-banner" role="alert"><AlertCircle size={18}/><span>{error}</span><button onClick={()=>void refresh()}>刷新状态</button><button className="icon-button" aria-label="关闭错误提示" onClick={()=>setError('')}><X size={16}/></button></div>}
 <div className="phase-path"><div className={current<=2?'active': 'passed'}><span>01</span><strong>把需求说清楚</strong><small>PRD → 提问 → 需求确认</small></div><ChevronRight size={18}/><div className={current>=3&&current<8?'active':''}><span>02</span><strong>按轮次推进开发</strong><small>文档 → 确认 → 书签 → 开发 → 验收</small></div><ChevronRight size={18}/><div className={current===8?'active':''}><span>03</span><strong>逐步完成产品</strong><small>下一轮文档，继续同一流程</small></div></div>
 {loading?<div className="loading-panel"><LoaderCircle className="spin"/>正在恢复你的进度…</div>:<div className="workflow-layout"><aside className="flow-rail"><div className="rail-heading">项目推进<span>{project?`第 ${project.round} 轮`:'从这里开始'}</span></div><ol>{workflowSteps.map((s,i)=>{const Icon=stepIcons[i];const done=i<current||project?.workflow==='completed';const active=i===current;return <li key={s.key} className={`${active?'active':''} ${done?'done':''} ${i===3?'round-start':''}`}>{i===3&&<div className="rail-divider"><RotateCcw size={12}/>第 {project?.round||1} 轮 · {project?stages[project.stage].name:'开发'}</div>}<button disabled={!done&&!active} aria-current={active?'step':undefined} onClick={()=>setView(active?'flow':'history')}><span className="flow-node">{done?<Check size={16}/>:<Icon size={17}/>}</span><span className="flow-node-text"><strong>{s.label}</strong><small>{active?project?.status==='running'?'正在进行':project?.status==='failed'?'需要处理':'当前步骤':done?'已完成':s.description}</small></span>{!active&&!done&&<Lock className="rail-lock" size={12}/>}</button></li>;})}</ol><div className="loop-note"><CornerDownRight size={17}/><span>验收通过后<br/><b>回到下一轮技术文档</b></span></div><div className="rail-foot"><ShieldCheck size={14}/>后续步骤按顺序解锁</div></aside>
 <div className="flow-workspace">{view==='history'&&project?<><button className="back-flow" onClick={()=>setView('flow')}><Route size={15}/>回到当前步骤：{title}<ArrowRight size={15}/></button><Records p={project}/></>:<>
 <div className="current-step-heading"><div className="step-overline"><span>STEP {String(Math.min(current+1,8)).padStart(2,'0')}</span><i/>{current<=2?'需求对齐':`第 ${project?.round||1} 轮 · ${project?stages[project.stage].name:'开发'}`}<span className="step-owner">{current===0?'你来提供':current===1?'AI 与你一起':current===3?'AI 来整理':current===5?'系统保存':current===6?'AI 来执行':'由你确认'}</span></div><h2>{title}</h2><p>{descriptions[current]||'所有阶段已验收，项目文件和推进记录保存在本机。'}</p></div>
 {!project?<><section className={`upload-card flow-upload ${drag?'drag-active':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={drop}><button className="drop-zone" disabled={uploading} onClick={()=>input.current?.click()}><div className="upload-icon"><FileText size={33}/><span><Plus size={14}/></span></div><h3>{uploading?'正在读取 PRD…':drag?'松开文件，开始需求澄清':'把你的 PRD 拖到这里'}</h3><p>或点击选择文件</p><div className="file-types"><span>Markdown</span>{!previewMode&&<><span>Word</span><span>PDF</span></>}<span>TXT</span><i>最大 10 MB</i></div></button><div className="upload-bottom"><span><Lock size={13}/>文件保存在本机</span><button onClick={()=>download('PRD模板.md',template)}>还没写 PRD？下载模板<Download size={14}/></button></div></section><div className="next-step-preview"><span className="next-icon"><MessagesSquare size={21}/></span><div><span className="eyebrow">接下来 · STEP 02</span><h3>模型先提问，你来补全需求。</h3><p>不会直接开始写代码。需求确认后，才会生成第一轮技术文档。</p></div><ArrowDown size={20}/></div><p className="model-consent">{previewMode?'这是交互演示。你的 PRD 不会上传到服务器；完整模型与代码开发功能请运行本机版本。':'拖入后将使用本机 Codex 阅读 PRD，可能消耗已配置账号的额度。需求与技术文档整理使用只读模式。'}</p></>:<>
 {project.error&&<div className="inline-warning"><AlertCircle size={18}/><span>{project.error}</span></div>}
 <section className="flow-card" key={`${project.id}-${project.workflow}-${project.version}-${project.interviewTurn}`}>
 {project.status==='running'?<div className="working-state"><span className="working-orbit"><LoaderCircle className="spin" size={28}/></span><span className="eyebrow">{project.job==='develop'?'DEVELOPING':'THINKING THROUGH YOUR PROJECT'}</span><h3>{project.job==='analyze'?'模型正在阅读并梳理需求':project.job==='plan'?'正在编写本轮技术文档':'正在按已确认的技术文档开发'}</h3><p>{project.job==='analyze'?'整理清楚后，会在这里向你提问或请你确认需求。':project.job==='plan'?'完成后会停下来，等你审阅并确认文档。':'完成后会停在验收，不会自动进入下一轮。'}</p><div className="working-boundary"><Lock size={14}/>{project.job==='develop'?`仅授权第 ${project.round} 轮`:'当前是只读分析，不修改业务代码'}</div><button className="button secondary" disabled={busy} onClick={()=>void act({action:'cancel'})}><Square size={13}/>暂停当前步骤</button></div>:
 project.workflow==='questions'?(project.questions.length?<Questions p={project} busy={busy} act={act}/>:<div className="waiting-state"><span className="empty-step-icon"><MessagesSquare size={30}/></span><h3>先让模型理解你的产品</h3><p>模型会检查 PRD 中的目标、范围和验收标准。<br/>有缺口时，每轮向你提出最多 5 个必要问题。</p><div className="input-received"><FileText size={17}/><span>{project.filename}</span><CheckCircle2 size={16}/><small>已收到</small></div><button className="button primary" disabled={busy} onClick={()=>void act({action:'analyze'})}>{project.status==='failed'?'重新进行需求体检':'开始模型提问'}<ArrowRight size={16}/></button><small>需求未确认 · 技术文档和开发尚未开始</small></div>):
 project.workflow==='requirements'?<Requirements p={project} busy={busy} act={act}/>:
 project.workflow==='planning'?<div className="waiting-state"><span className="empty-step-icon"><FileText size={30}/></span><h3>依据已确认需求，编写本轮方案</h3><p>模型会结合已有代码与技术手册，说明这轮做什么、<br/>怎么实现、如何验收，以及有哪些费用与风险。</p><button className="button primary" disabled={busy} onClick={()=>void act({action:'plan'})}>生成第 {project.round} 轮技术文档<ArrowRight size={16}/></button><small>文档生成后需要你确认</small></div>:
 project.workflow==='document'?<DocumentReview p={project} busy={busy} act={act}/>:
 project.workflow==='bookmark'?<div className="bookmark-step"><div className="completed-dependency"><CheckCircle2 size={19}/><div><strong>前一步：技术文档已确认</strong><p>第 {project.round} 轮 · {stages[project.stage].name} · v{project.version}</p></div></div><div className="bookmark-explanation"><span className="empty-step-icon"><Bookmark size={31}/></span><h3>在改变代码之前，留下一个版本。</h3><p>{previewMode?'演示版仅保存浏览器中的流程记录，不包含代码，不会创建 Git commit。':'保存当前项目的完整 Git 快照，并关联到刚刚确认的技术文档。'}<br/>这份书签是本轮开发的起点。</p><div className="inline-sequence"><span className="done"><Check size={13}/>文档已确认</span><ArrowRight size={14}/><b>保存代码书签</b><ArrowRight size={14}/><span>开始开发</span></div></div><div className="flow-action"><div><span>保存成功后才能开发</span><small>不会覆盖或回滚现有代码</small></div><button className="button primary" disabled={busy} onClick={()=>void act({action:'bookmark'})}><Bookmark size={16}/>{previewMode?'保存演示流程快照':'保存本轮代码书签'}</button></div><button className="subtle-action" onClick={()=>void act({action:'revise',document:project.document})}><Pencil size={14}/>返回文档重新审阅</button></div>:
 project.workflow==='ready'?<><div className="ready-summary"><span className="ready-badge"><CheckCircle2 size={31}/></span><h3>本轮开发的前置步骤，全部完成。</h3><div className="prerequisites"><div><CheckCircle2 size={17}/><span>需求已确认</span></div><div><CheckCircle2 size={17}/><span>第 {project.round} 轮技术文档 v{project.version} 已确认</span></div><div><CheckCircle2 size={17}/><span>代码书签已保存 <code>{project.bookmarks[0]?.commit.slice(0,7)}</code></span></div></div><p>现在只执行文档约定的这一轮。开发结束后，等待你的验收。</p></div><div className="confirmation-area"><label className="confirm-check"><input type="checkbox" checked={devConsent} onChange={e=>setDevConsent(e.target.checked)}/><span>{previewMode?'我已了解这是流程演示，不调用模型，也不修改真实代码。':'允许本机 Codex 执行本轮开发，修改本项目代码并使用已有账号额度。'}</span></label></div><div className="flow-action"><div><span>下一站：验收本轮成果</span><small>不会自动进入下一轮</small></div><button className="button primary" disabled={busy||!devConsent} onClick={()=>void act({action:'develop',version:project.version,docHash:project.docHash,bookmarkId:project.bookmarks[0]?.id,confirmed:true})}><Play size={15}/>{previewMode?'演示':'开始'}第 {project.round} 轮开发</button></div><button className="subtle-action" onClick={()=>void act({action:'revise',document:project.document})}><Pencil size={14}/>方案有变，返回重新确认</button></>:
 project.workflow==='development'?<div className="waiting-state"><AlertCircle size={32}/><h3>本轮开发已暂停</h3><p>请检查已有代码与结果。重新审阅文档、保存书签后再继续。</p><button className="button primary" disabled={busy} onClick={()=>void act({action:'request_revision',feedback:'执行中断，请检查当前项目代码与原方案，重新整理本轮剩余范围和验证方法。'})}>重新准备本轮技术文档<ArrowRight size={16}/></button></div>:
 project.workflow==='review'?<Review p={project} busy={busy} act={act}/>:<div className="waiting-state"><CheckCircle2 size={40}/><h3>每一轮，都有清晰的来处。</h3><p>项目已完成。需求、技术文档、确认记录和代码书签均可回看。</p><button className="button secondary" onClick={()=>setView('history')}>查看项目记录<History size={16}/></button></div>}
 </section><div className="workflow-bottom"><span><ShieldCheck size={14}/>{current<=2?'需求确认后，才解锁技术文档':`第 ${project.round} 轮 · 完成当前步骤，再继续下一步`}</span><button onClick={()=>setView('history')}>回看前面的记录<History size={14}/></button></div>
 </>}
 </> }</div></div>}
 </div><footer className="footer"><span>STARTER STUDIO</span><p>PRD → 对齐需求 → 按轮次开发 → 完成产品</p><span>每一步，都经你确认</span></footer></main>
 <dialog ref={dialog} className="modal" onCancel={()=>setHelp(false)} onClick={e=>{if(e.target===dialog.current)setHelp(false);}}><div className="modal-content"><button className="modal-close icon-button" aria-label="关闭流程说明" onClick={()=>setHelp(false)}><X size={20}/></button><div className="modal-icon"><Route/></div><h2>这是一条推进流程。</h2><p>先把需求说清楚，再开始一轮轮开发。</p><div className="help-flow">PRD<ArrowDown size={17}/>模型提问 ↔ 你来回答<ArrowDown size={17}/>你确认需求<ArrowDown size={17}/><strong>技术文档 → 你确认文档<br/>↓<br/>保存代码书签 → 按文档开发<br/>↓<br/>你验收 → 下一轮技术文档</strong></div><p>文档与书签是每一轮的记录。没有完成前一步，后一步不会开始。</p><button className="button primary full-width" onClick={()=>setHelp(false)}>回到我的流程</button></div></dialog>
 {toast&&<div className="toast" role="status"><CheckCircle2 size={17}/>{toast}</div>}
 </div>;
}
function CommandIcon(){return <FolderOpen size={17}/>;}
