import fs from 'node:fs/promises';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
const root=process.cwd();
const stage=path.join(root,'.pages-build');
await fs.rm(stage,{recursive:true,force:true});
await fs.mkdir(path.join(stage,'app'),{recursive:true});
for(const file of ['package.json','tsconfig.json','next-env.d.ts'])await fs.copyFile(path.join(root,file),path.join(stage,file));
for(const file of ['page.tsx','layout.tsx','globals.css'])await fs.copyFile(path.join(root,'app',file),path.join(stage,'app',file));
for(const dir of ['components','public'])await fs.cp(path.join(root,dir),path.join(stage,dir),{recursive:true});
await fs.mkdir(path.join(stage,'lib'));
for(const file of ['api.ts','types.ts','preview-api.ts'])await fs.copyFile(path.join(root,'lib',file),path.join(stage,'lib',file));
await fs.symlink(path.join(root,'node_modules'),path.join(stage,'node_modules'),'dir');
const basePath=process.env.PAGES_BASE_PATH||'/starter-studio';
if(!/^\/[a-zA-Z0-9_-]+$/.test(basePath))throw new Error('PAGES_BASE_PATH must be a single safe path segment');
await fs.writeFile(path.join(stage,'next.config.mjs'),`export default ${JSON.stringify({output:'export',basePath,trailingSlash:true,images:{unoptimized:true},poweredByHeader:false,devIndicators:false,agentRules:false,turbopack:{root}})};\n`);
const result=spawnSync(process.execPath,[path.join(root,'node_modules/next/dist/bin/next'),'build',stage],{stdio:'inherit',env:{...process.env,NEXT_PUBLIC_STUDIO_PREVIEW:'1',NEXT_PUBLIC_BASE_PATH:basePath}});
if(result.status!==0)process.exit(result.status||1);
await fs.rm(path.join(root,'out'),{recursive:true,force:true});
await fs.cp(path.join(stage,'out'),path.join(root,'out'),{recursive:true});
await fs.writeFile(path.join(root,'out','.nojekyll'),'');
console.log('GitHub Pages build ready in out/');
